/*
 * Device.h
 *
 *  Created on: Apr 23, 2013
 *      Author: ruinmmal
 */

#ifndef DEVICE_H_
#define DEVICE_H_

#include "DeviceChannel.h"
#include "Sensor.h"

#include "DataLoggerThread.h"
#include "EventLoggerThread.h"
#include "CmdLoggerThread.h"

#include <list>

//consists of channels and sensors. each sensor has its own channels
class Device {
protected:
	std::list<Sensor*> m_sensorList;
	std::list<DeviceChannel*> m_deviceChannelList;
	int m_deviceId; // ID generated by installation system. Not set until passed from command line
public:
	Device();
	virtual ~Device();
	bool AddSensor(Sensor* pSensor);
	bool AddChannel(DeviceChannel* pChannel);
	const std::list<Sensor*>& getSensors() const { return m_sensorList; };
	const std::list<DeviceChannel*>& getChannels() const { return m_deviceChannelList; };
	void setDeviceId(int devId) { m_deviceId = devId; };
	int getDeviceId() { return m_deviceId; };
	virtual bool Run(EventLoggerThread* pEvtLogger, CmdLoggerThread* pCmdLogger, DataLoggerThread* pDataLogger) {};
};

#endif /* DEVICE_H_ */
